repos:
  - repo: https://github.com/biomejs/pre-commit
    rev: "v0.5.0" # Use the sha / tag you want to point at
    hooks:
      - id: biome-check
        additional_dependencies: ["@biomejs/biome@1.6.2"]
