version: "3"
services:
  traefik:
    restart: unless-stopped
    image: traefik:latest
    command: --providers.docker=true
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  firebolt-demo:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.http.routers.firebolt-demo.rule=Host(`firebolt-demo.traefik.me`)"
      - "traefik.http.services.firebolt-demo.loadbalancer.server.port=3000"
    environment:
      PORT: 3000
