# fly.toml app configuration file generated for firebolt-demo on 2024-03-24T14:41:06+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'firebolt-demo'
primary_region = 'sin'

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[checks]
[checks.api_health_check]
grace_period = "30s"
interval = "15s"
method = "get"
path = "/api/health"
port = 3000
timeout = "10s"
type = "http"

[[vm]]
size = 'shared-cpu-1x'
